[build]
  publish = "public"
  command = "hugo --minify --gc"

[build.environment]
  HUGO_VERSION = "0.92.2"
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 